### ISSUE TITLE
Returns error when trying to run AlphInts(20,c(204,269,2016), lev=0.9)

### ISSUE THREAD

**Issue by jamesjcai** [kpmainali/CooccurrenceAffinity#5]
I tried AlphInts(20,c(204,269,2016), lev=0.9, scal=10) but still got the same error. Thank you if you could let me know how to fix this.

**Comment by kpmainali** [comment]
Hello, thank for bringing this to our attention. The error stems from the dependency we use.  On Jul 12, 2022, we added a new function minmaxAlpha.pFNCH(). Without this function, BiasedUrn::pFNCHHypergeo() returns inconsistency message for extreme examples like: AlphInts(20,c(204,269,2016), lev=0.9, scal=10). This problem is solved within our package by restricting the range of allowed alpha to the computed (alphmin, alphmax) range.
